### ISSUE TITLE
Improve process filter

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1734]
- [x] More predicates https://github.com/mesg-foundation/engine/pull/1738
- [x] More type value: https://github.com/mesg-foundation/engine/issues/1569
- [x] Add the reference system: https://github.com/mesg-foundation/engine/issues/1582
- [x] Update compiler/yaml definition 
  - https://github.com/mesg-foundation/js-sdk/issues/200
  - https://github.com/mesg-foundation/js-sdk/pull/205
- [x] update doc: https://github.com/mesg-foundation/docs/pull/118

Removed from current sprint:
- [ ] Add node reference system to process node result as well https://github.com/mesg-foundation/engine/issues/1562
